# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default='#f3f3f3', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.Category')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_content.category_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContentFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.URLField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='content.Category')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_content.contentfeed_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimestampedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedArticle',
            fields=[
                ('timestampedarticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.TimestampedArticle')),
                ('identifier', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.timestampedarticle',),
        ),
        migrations.AddField(
            model_name='timestampedarticle',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='content.Category'),
        ),
        migrations.AddField(
            model_name='timestampedarticle',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_content.timestampedarticle_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='timestampedarticle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ContentSource'),
        ),
        migrations.AddField(
            model_name='contentfeed',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ContentSource'),
        ),
        migrations.CreateModel(
            name='KidsWeekFeed',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('content.contentfeed',),
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('content.contentfeed',),
        ),
        migrations.CreateModel(
            name='SevenDaysFeed',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('content.contentfeed',),
        ),
    ]
